name: Terraform Security and CIs

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

permissions:
  contents: read
  security-events: write  # Needed to upload Snyk results to GitHub Code Scanning

jobs:
  terraform-code-scan:
    runs-on: ubuntu-latest
    name: Terraform Code Quality and Security

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.3

      - name: Cache Terraform plugins
        uses: actions/cache@v3
        with:
          path: .terraform
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf') }}
          restore-keys: ${{ runner.os }}-terraform-

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Setup tflint
        uses: terraform-linters/setup-tflint@v1
        with:
          tflint_version: v0.40.0

      - name: Run tflint
        run: tflint --init && tflint

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk to check Terraform for vulnerabilities
        uses: snyk/actions/iac@v0.4.0
        with:
          args: --scan=terraform --sarif-file-output=snyk.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload Snyk SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

      - name: Upload Terraform Files as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-code
          path: |
            **/*.tf
            **/*.tfvars

      - name: Show downloaded files
        run: |
          ls -R    
          pwd
