name: Terraform Security and CI

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  terraform-format:
    runs-on: ubuntu-latest
    name: Terraform Format Check

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

  terraform-lint:
    runs-on: ubuntu-latest
    needs: terraform-format
    name: Terraform Lint (tflint)

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.3

      - name: Setup tflint
        uses: terraform-linters/setup-tflint@v1
        with:
          tflint_version: v0.40.0

      - name: Run tflint
        run: tflint --init && tflint

  terraform-security:
    runs-on: ubuntu-latest
    needs: terraform-lint
    name: Terraform Security Scan with Snyk

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Snyk
        uses: snyk/actions/setup@v1.2.0

      - name: Run Snyk to check Terraform for security issues
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk iac test --report --report-format=sarif --sarif-file-output=snyk.sarif

      - name: Upload Snyk SARIF Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

  terraform-init:
    runs-on: ubuntu-latest
    needs: terraform-security
    name: Terraform Init

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.3

      - name: Terraform Init
        run: terraform init

  terraform-validate:
    runs-on: ubuntu-latest
    name: Terraform Validate
    needs: terraform-init

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.3

      - name: Terraform Validate
        run: terraform validate
