name: Terraform Security and CIs

on:
  push:
    branches: development
  pull_request:
    branches: development

jobs:
  terraform-code-scan:
    runs-on: ubuntu-latest
    name: Terraform Code Quality and Security

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Setup tflint
        uses: terraform-linters/setup-tflint@v1
        with:
          tflint_version: v0.40.0  # Try an updated tflint version

      - name: Run tflint
        run: tflint --init && tflint

      - name: Run tfsec (security scan)
        uses: aquasecurity/tfsec-action@v1.0.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Upload Terraform Files as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-code
          path: |
            *.tf
            *.tfvars
            
      - name: Show downloaded files
        run: |
            ls -R    
            pwd

  push-artifact-to-repo:
    needs: terraform-code-scan
    runs-on: ubuntu-latest
    if: success()  # Only run if previous job was successful

    steps:
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: AshwiniDevOpz/Artefact_Storage # or current repo if pushing to another branch
          ref: main  # Or another target branch
          token: ${{ secrets.My_GITHUB_TOKEN }}  # Or a personal access token if needed
          path: Artefact_Storage/

      - name: Download Terraform artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-code
          path: terraform-code

      - name: Copy files to repo
        run: |
          cp -r terraform-code/* Artefact_Storage//

      - name: Commit and push changes
        run: |
          cd Artefact_Storage/
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Add Terraform code from artifact"
          git push
